import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "./_component/Wrapper";
import FixedOverlay from "./_component/FixedOverlay";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full scroll-smooth bg-white scroll-pt-[3.5625rem]">
      <body className={`${inter.className} h-full bg-white font-sans text-gray-900 antialiased`}>
        <FixedOverlay />
        <Wrapper>
          {/* <Headerv2 /> */}
          {children}
        </Wrapper>
        </body>
    </html>
  );
}
