import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "./_component/Wrapper";
import Header from "./_component/Header";
import FixedOverlay from "./_component/FixedOverlay";
import Headerv2 from "./_component/Headerv2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full bg-white font-sans text-gray-900 antialiased`}>
        <FixedOverlay />
        <Wrapper>
          <Header />
          {/* <Headerv2 /> */}
          {children}
        </Wrapper>
        </body>
    </html>
  );
}
